exclude:
  - app/content/articles/models/**

linters:
  SpaceAroundErbTag:
    enabled: true
  ClosingErbTagIndent:
    enabled: false
  AllowedScriptType:
    enabled: false
  NoJavascriptTagHelper:
    enabled: false
  RequireInputAutocomplete:
    enabled: false
