detectors:
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    enabled: false
  MissingSafeMethod:
    enabled: false
  NilCheck:
    enabled: false
  UncommunicativeVariableName:
    enabled: false
  TooManyStatements:
    max_statements: 8
    exclude:
      - initialize
  LongParameterList:
    max_params: 4
  FeatureEnvy:
    enabled: true
  NestedIterators:
    max_allowed_nesting: 2
  DataClump:
    enabled: true
  DuplicateMethodCall:
    max_calls: 2
  TooManyMethods:
    max_methods: 20

exclude_paths:
  - test/
  - db/migrate/
  - config/
